#version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
      - "35729:35729" # <-- Questa è la porta standard usata da Webpack per il Live Reload!
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true # <-- Aggiungiamo anche questa per sicurezza (usata dalle vecchie versioni)
      - WDS_SOCKET_PORT=3000 # <-- Forza il socket a usare la porta principale se la principale è la 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # Ricomponiamo la stringa di connessione usando le variabili
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
